name: RSS Analyzer

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  rss-analyzer:
    runs-on: ubuntu-latest

    steps:
      - name: Repo klonla
        uses: actions/checkout@v4

      - name: Python quraşdır
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Kitabxanaları quraşdır
        run: |
          pip install requests beautifulsoup4 feedparser

      - name: RSS-ləri avtomatik tap
        run: |
          python rss_analyzer.py
